name: Snyk Node.js Scan

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  snyk-node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # Needed for SARIF upload

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://github.com/snyk/snyk/releases/latest/download/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYKTOKEN }}

      - name: Run Snyk test and capture result
        id: snyk-test
        run: |
          snyk test --file=package.json \
                    --severity-threshold=high \
                    --sarif-file-output=snyk-node.sarif || echo "SNYK_TEST_FAILED=true" >> $GITHUB_ENV

      - name: Monitor project in Snyk
        run: snyk monitor --file=package.json

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-node.sarif

      - name: Fail job if Snyk test failed
        if: env.SNYK_TEST_FAILED == 'true'
        run: |
          echo "High or critical vulnerabilities detected. Failing the build."
          exit 1
